services:
  pgvector:
    image: ankane/pgvector
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  app_data: